language: java
jdk:
- oraclejdk8

env:
  global:
    - secure: V43x7qLAIR04tiDBA7Y2v4RVjbj7ATIm9+ilXjRdaBPpjigRZ5dYQqmGOTs5aIR1JhDiU/dF9uIObzo82epQAnSlOUz138S6AAyTvq3H6vfwPUz6jcNxYlP36rdmRNJa9aXjlNKB8zxmAhOwl0c4S+YYad2LyAanDq6PEMa2vlEqIWDpiJ5YIVjH1UeY6cSpofSc4rTUTJBE6zoNIic9gWTEBRNKuvNCn0ojVlVBJjHnwAVskqot5d8e9EDvp/d3CDfZm2ZhBUzXakvHueQWbXMuysrSapsWlZsgVyXhc2N21zRjZZ8EFp8Pomz7PWYrbOcaAM49jKRgYPFHX/6uVAhoUNhUoEWAA2I7RXSc8gIXSRHI3zZQtIU8QwrvUaacNY0N3ffe2kRWnwhSK+CKqeBx2HuIw/Jv7qHI1Gg6u4907HCut/gt6t0nB7rJ30DxdQ5naTPVzy/oKQiSYLRrBgJHR+yLcs7qj9BCrMarCsR5ev4OCNCdlJuebrda8v8wEcrjlWRHLHlt+DhkGrcIbty1kaSBYC3/OAAmR5Y4yfOyadhEdkLZFQXet9xFlTaV4VD/4X6iwQ8SmS/rb09NWfFiy50KseaywJy/r+1VlefdpSPAi/nrbG6BZeYQkjh0L95opgFYs5rFBNcdhlpRcsv1DyvVmcmTijwy2c4j1JQ=
    - secure: bSkR/FIHTu4SWd8ay1sKX4EKFjcwz+kVYNir/JPKaMEYPlvsypxFRcLvpipUHW+bEaPudQhNuHKcoPiqMFc79/XVVeMmSy4IIJQ8oEAWZd/W0P8JO9pi2yRfUs0yZWxLwX0Fus5wULVbNjakNgpp5rB4dOggwnM08dy3A4oGKFZitSIRBqnrAqmkWCebTDjP+6NruFl5yXXXd7/7WoL0d66DrS+bhDajNtsicjFmHU5zEIFOdmAnF+O6h1+0EKa8E8qMibWkTz2AmY7iXwwxzvstsoVzM67oEBdy/ur8yJLbkmgERdO17nHxKSXhx7Z1IBCNyPlORYweULm1qRO1sF9EQOWIEmRemlBZD3GctdHcX+ck/XBK1/WQ9Twb4Np5n0++hyul9xZtTDVxKmjjPLj8FL+BHQj42rZNxpu7eDmZEJx1VMX2lHTYwCDTGl+cMCO1yXQUYepk5WivcE5lDpq+cqg4x1qM6TmCyyT/BAjqqk0SHujxk4Jf8dhwqP8bwrvqqv8id4hHKD15kA1ulF2m6tsTirNN/LqmwYTzTPfM+1iZqyRYfoQCMLQzOd7giegkJIIE4UWHxnn3B1bVVlywXuqN9zOtg+KlWqfh/WWctuYrluyMclA19KXFxLqcKic/DoPLQ2RRTMgdlpzNwB87w5xi4p6GsS7wBR8XXPY=
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

sudo: required

services:
  - docker

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw install -DskipTests -Dgpg.skip

script:
  - ./mvnw test && ./ui/build.sh

after_success:
  - if [ "$BRANCH" == "master" ]; then
    docker build -t logzio/apollo:$TRAVIS_COMMIT .;
    docker tag logzio/apollo:$TRAVIS_COMMIT logzio/apollo:latest
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push logzio/apollo:$TRAVIS_COMMIT;
    fi
